language: dart
dart:
  - stable
  - dev
script:
  - pub global activate coverage
  - dart -c --observe test/storey_test.dart &
  - pub global run coverage:collect_coverage --resume-isolates --wait-paused -o coverage.json
  - pub global run coverage:format_coverage --packages=.packages --report-on lib --in coverage.json --out lcov.info --lcov
after_success:
  - bash <(curl -s https://codecov.io/bash)
dart_task:
  - test: --platform vm
  - dartanalyzer: --fatal-warnings .
