language: dart
dart:
  - stable
  - dev
script:
  - pub run dart_dev coverage --no-html
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
dart_task:
  - test: --platform vm
  - dartanalyzer: --fatal-warnings .
