name: storey
description: Redux like store but hierarchical.
version: 0.0.1
homepage: https://github.com/kezhuw/storey
author: Kezhu Wang <kezhuw@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  meta: ^1.1.1

dev_dependencies:
  test: ^0.12.0
